[package]
name = "morrow-runtime"
version = "0.1.0"
edition = "2021"
description = "Morrow Runtime Core — Rust cdylib for Minecraft native modding"

[lib]
crate-type = ["cdylib"]

[dependencies]
zip = "2"
toml = "0.8"
serde = { version = "1", features = ["derive"] }
libloading = "0.8"
log = "0.4"
tempfile = "3"
